# -- Plugin List --
#set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-tokyo-night/tmux-powerkit.tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-floax'
if-shell 'test "$(uname -s)" = "Darwin"' "set -g @plugin 'barlevalon/tmux-nowplaying-macos'"
set -g @plugin 'mrjones2014/smart-splits.nvim'
# set -g @plugin 'xamut/tmux-weather' # Example of a commented out plugin


# -- Plugin Configurations --

# tmux-floax (floating window)
set -g @floax-bind 'p'

# nowplaying-macos (macOS only)
set -g @nowplaying_scrolling_enabled "yes"
set -g @nowplaying_auto_interval "yes"
set -g @nowplaying_scrollable_threshold 25
set -g @nowplaying_scroll_speed 2

# smart-splits.nvim (for Neovim navigation)
set -g @smart-splits_move_left_key  'C-h'
set -g @smart-splits_move_down_key  'C-j'
set -g @smart-splits_move_up_key    'C-k'
set -g @smart-splits_move_right_key 'C-l'

set -g @smart-splits_resize_left_key  'M-h'
set -g @smart-splits_resize_down_key  'M-j'
set -g @smart-splits_resize_up_key    'M-k'
set -g @smart-splits_resize_right_key 'M-l'


# Run the plugin's script
if-shell 'test -r ~/.config/tmux/plugins/tmux-floax/floax.tmux' \
  'run ~/.config/tmux/plugins/tmux-floax/floax.tmux'
# Load the theme script (plugins like Catppuccin often need to be run)
#run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
if-shell 'test -r ~/.config/tmux/plugins/tmux-tokyo-night/tmux-powerkit.tmux' \
  'run ~/.config/tmux/plugins/tmux-tokyo-night/tmux-powerkit.tmux'
